services:
  - type: web
    name: free-id-card-service
    env: python
    buildCommand: |
      pip install poetry
      poetry install --no-root
    startCommand: poetry run gunicorn app:app
